Rename master->main

diff --git a/bin/mina-deploy b/bin/mina-deploy
--- a/bin/mina-deploy
+++ b/bin/mina-deploy
@@ -17,7 +17,7 @@ cd "$dir" \
     && git fetch -p \
     && git checkout "$branch" \
     && git pull origin "$branch" \
-    || fail "Might need to do: (cd $dir && git merge --abort && git checkout master && git branch -D '$branch')"
+    || fail "Might need to do: (cd $dir && git merge --abort && git checkout main && git branch -D '$branch')"
 
 export RAILS_ENV=development
 export NODE_OPTIONS='--max-old-space-size=5120'
